#!/bin/bash
set -exuo pipefail

rm -f ./*.zip

zip -9 --junk-paths ./api.zip api/script/kv-api api/bin/linux/api

zip -9 --junk-paths ./bootstrap.zip infra/script/*.sh

aws s3 cp ./api.zip s3://kv-artifacts-us-west-2/
aws s3 cp ./bootstrap.zip s3://kv-artifacts-us-west-2/
