---
AWSTemplateFormatVersion: 2010-09-09

Description: API ASG

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to instance
      VpcId: !ImportValue kv-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupId:
    Value: !Ref SecurityGroup
    Export:
      Name: kv-bastion-security-group-id
