---
AWSTemplateFormatVersion: 2010-09-09

Description: Consul Security Groups

Resources:
  ClientSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to the cluster
      VpcId: !ImportValue kv-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8300
          ToPort: 8300
          SourceSecurityGroupId: !Ref ClusterSecurityGroup
        - IpProtocol: tcp
          FromPort: 8301
          ToPort: 8302
          SourceSecurityGroupId: !Ref ClusterSecurityGroup
        - IpProtocol: udp
          FromPort: 8301
          ToPort: 8302
          SourceSecurityGroupId: !Ref ClusterSecurityGroup
        - IpProtocol: tcp
          FromPort: 8500
          ToPort: 8500
          SourceSecurityGroupId: !Ref ClusterSecurityGroup
        - IpProtocol: tcp
          FromPort: 8600
          ToPort: 8600
          SourceSecurityGroupId: !Ref ClusterSecurityGroup
        - IpProtocol: udp
          FromPort: 8600
          ToPort: 8600
          SourceSecurityGroupId: !Ref ClusterSecurityGroup

  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow for cluster member communications
      VpcId: !ImportValue kv-vpc-id

Outputs:
  ClientSecurityGroupId:
    Value: !Ref ClientSecurityGroup
    Export:
      Name: kv-consul-client-security-group-id
  ClusterSecurityGroupId:
    Value: !Ref ClusterSecurityGroup
    Export:
      Name: kv-consul-cluster-security-group-id
