# Gopkg.toml example
#
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.4"

[prune]
  go-tests = true
  unused-packages = true
